### ISSUE TITLE
Rename actions btn on form doesn't work

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/react-forms#52]
`
const actions= {
    submit: {
      label:"sauver", 
      display:true
    }
  }

...

      <Form schema={schema} className="form" onSubmit={window.alert} actions={actions} />
`

<img width="269" alt="image" src="https://user-images.githubusercontent.com/27761959/159893780-831bc2d5-e651-4dcf-af82-f2056fafbacf.png">

**Comment by quentinovega** [comment]
use options instead actions
